name: be_ready_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  syncfusion_flutter_sliders:
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  google_sign_in: ^5.4.2
  flutter_facebook_auth: ^5.0.6
  sign_in_with_apple: ^3.0.0
  http:




  reusables:
    git: https://github.com/SparkoSol/reusables.git
  image_picker: ^0.8.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700